name: Deploy Astro

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun run build

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - run:
          python -m pip install --upgrade pip
          python -m pip install fonttools brotli

      - name: Upload files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SOURCE: "dist/"
          TARGET: "/www/wwwroot/unleafy.cn"